version: '2'

services:
  mongodb_primary:
      hostname: mongodb
      image: mongo:3.2.8
      volumes:
        - /mnt/Documents/Workspace/Perso/MongoCourse/log/rs1:/home/anael/log
      ports:
        - "27017:27017"
      depends_on:
        - "mongodb_secondary_2"
      command: --replSet my-mongo-set

  mongodb_secondary_1:
      hostname: mongodb
      image: mongo:3.2.8
      volumes:
        - /mnt/Documents/Workspace/Perso/MongoCourse/log/rs2:/home/anael/log
      ports:
        - "27018:27017"
      depends_on:
        - "mongodb_primary"
      command: --replSet my-mongo-set

  mongodb_secondary_2:
      hostname: mongodb
      image: mongo:3.2.8
      volumes:
        - /mnt/Documents/Workspace/Perso/MongoCourse/log/rs3:/home/anael/log
      ports:
        - "27019:27017"
      command: --replSet my-mongo-set

  mongosetuper:
      hostname: mongodb
      image: mongo:3.2.8
      ports:
        - "27020:27017"
      volumes:
        - /mnt/Documents/Workspace/Perso/MongoCourse/scripts:/scripts
      depends_on:
        - "mongodb_secondary_1"
      entrypoint: [ "/scripts/setupReplicatSet.sh" ]
      tty: true
