version: '2'

services:
  mongodb_primary:
      hostname: mongodb
      image: mongo:3.2.8
      volumes:
        - /mnt/Documents/Workspace/Perso/MongoCourse/log/rs1:/home/anael/log
      ports:
        - "27017:27017"
      command: --smallfiles